Consultorio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView,logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("general.urls", namespace="home")),
    path('medico/',include('Medicos.urls')),
    path('paciente/',include('pacientes.urls')),

    path('accounts/login/',LoginView.as_view(template_name='paginas/login.html'),name='login'),
    path('logout/',logout_then_login,name='logout'),
]

Medicos/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import UsuarioRegistro, DirectorSeccion, ListMedicos, \
    ListServicios, CreateServicios, MedicoRegistro, DListMedicos, \
    DListServicios, DirectorUpdateMedico, EliminarMedico, DirectorUpdateServicio, \
    EliminarServicio

app_name='Medicos'
urlpatterns = [

    path('director/', DirectorSeccion.as_view(), name="Seccion_Director"),

    path('listMedicos/', ListMedicos.as_view(), name="List_Medicos"),
    path('dListaMedicos/', DListMedicos.as_view(), name="DLista_Medicos"),
    path('listServicios/', ListServicios.as_view(), name="List_Servicios"),
    path('dListaServicios/', DListServicios.as_view(), name="DLista_Servicios"),

    path('usuarioRegistro/',UsuarioRegistro.as_view(),name='Usuario_Registrar'),
    path('crearServicio/', CreateServicios.as_view(), name= "Crear_Servicio"),
    path('medicoRegistro/', MedicoRegistro.as_view(), name= "Medico_Registrar"),

    path('dUpdateMedico/<int:pk>/', DirectorUpdateMedico.as_view(), name="DUpdate_Medico"),
    path('dUpdateServicio/<int:pk>/', DirectorUpdateServicio.as_view(), name="DUpdate_Servicio"),

    path('EliminarMedico/<int:pk>/', EliminarMedico.as_view(), name="Eliminar_Medico"),
    path('EliminarServicio/<int:pk>/', EliminarServicio.as_view(), name="Eliminar_Servicio"),
]

general/urls.py
from django.urls import path

from general import views

app_name = "paginas"

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('informacion', views.Informacion.as_view(), name="Informacion"),
]

pacientes/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import CrearConsulta, CrearCita, CrearReceta, MedicoConsultarCitas, BitacorasSeccion, \
    DirectorListaRecetas, DirectorListaPacientes, DirectorListaCitas, MedicoConsultarRecetas, \
    GeneratePDF, MedicoCitasCreadas, GeneratePDF2

app_name='Pacientes'

urlpatterns = [
    path('listaBitacoras/', BitacorasSeccion.as_view(), name="Lista_Bitacoras"),

    path('crearConsulta/', CrearConsulta.as_view(), name="Crear_Consulta"),
    path('crearCita/', CrearCita.as_view(), name="Crear_Cita"),
    path('crearReceta/', CrearReceta.as_view(), name="Crear_Receta"),

    path('consultarCitas/<int:pk>/', MedicoConsultarCitas, name="Consultar_citas"),
    path('consultarRecetas/<int:pk>/', MedicoConsultarRecetas, name="Consultar_recetas"),
    path('citasCreadas/<int:pk>/', MedicoCitasCreadas, name="Citas_Creadas"),

    path('listaRecetas/', DirectorListaRecetas.as_view(),name="Director_Lista_Recetas"),
    path('listaPacientes/', DirectorListaPacientes.as_view(),name="Director_Lista_Pacientes"),
    path('listaCitas/', DirectorListaCitas.as_view(),name="Director_Lista_Citas"),

    path('recetaPDF/<int:pk>/', GeneratePDF.as_view(), name="Receta_PDF"),
    path('citaPDF/<int:pk>/', GeneratePDF2.as_view(), name="Cita_PDF"),
]

templates/consultas/cita.html
<style>
 .titulos{
  font-size:20px;
  font-family:'Courier New';

  }
  .relleno{
  font-size:15px;
  font-family:'Courier New';
  text-decoration: underline;
  }
  .derecha{
  text-align:right;
  }
  .izquierda{
  text-align:left;
  }

</style>


{% csrf_token %}
{% for cit in citas %}
<div id="encabezado">
 <p class="derecha">
 <span class="titulos">Fecha creado: </span> <span class="relleno">{{ cit.fecha_creada|date:"F d Y" }}</span>
 </p>
<br>
</div>
{% endfor %}


 {% for med in medico %}
 <span class="titulos">Medico:</span> <span class="relleno">{{ med.nombre }} {{ med.apellido_p }} {{ med.apellido_m }}</span>

{% endfor %}


{% for cit in citas %}
 <span class="titulos">Paciente:</span> <span class="relleno">{{ cit.nombre_paciente }}</span>
<p></p>
{% endfor %}

{% for cit in citas %}
<span class="titulos">Cita en area de:</span> <span class="relleno">DR.{{ cit.servicio }}</span>
<p></p>
{% endfor %}

 {% for cit in citas %}
 <span class="titulos">Fecha y hora:</span>  <span class="relleno">{{ cit.dia_hora_cita }}</span>
<p></p>
<p class="titulos" style="text-align:right">Firma del medico: ___________________</p>
{% endfor %}

templates/consultas/citas_creadas.html
{% extends "base.html" %}

{% block title %}Citas{% endblock title %}

{% block content %}
  <table class="table table-striped">
      <th>ID</th>
      <th>Fecha Creado</th>
      <th>Creado Por</th>
      <th>Paciente</th>
      <th>Especialista</th>
      <th>Fecha y hora cita</th>
      <th></th>
    {% for cit in citas %}
      <tr>
          <td>{{ cit.id }}</td>
          <td>{{ cit.fecha_creada }}</td>
          <td>{{ cit.creada_por }}</td>
          <td>{{ cit.nombre_paciente }}</td>
          <td>{{ cit.servicio }}</td>
          <td>{{ cit.dia_hora_cita }}</td>
          <td>
              <a href="{% url 'Pacientes:Cita_PDF' cit.id %}"><button type="button" id="btnEditar" class="btn btn-success btn-circle"><i class="fas fa-print fa-sm"></i></button></a>
          </td>
      </tr>
    {% endfor %}
  </table>


{% endblock content %}

templates/consultas/crear_cita.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Crear cita{% endblock title %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-3"></div>
			<div class="card col-6 my-4">
				<div class="card-header" style="background-color: #007fba; font-size: 18px;">
					<p class="text-center font-weight-bold" style="color: #fff;">Crear cita nueva</p>
				</div>
				<div class="card-body">
					<form class="" action="" method="post">
  						{% csrf_token %}
  						{{ form|crispy }}
						<div class="form-group">
							<button class="btn btn-dark" type="submit ">Guardar</button>
							<a  href="{% url 'paginas:home' %}" class="btn btn-light" type="submit ">Cancelar</a>
						</div>
					</form>
				</div>
			</div>
	</div>
</div>
{% endblock content %}

templates/consultas/crear_receta.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Crear receta{% endblock title %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-3"></div>
			<div class="card col-6 my-4">
				<div class="card-header" style="background-color: #007fba; font-size: 18px;">
					<p class="text-center font-weight-bold" style="color: #fff;">Crear receta</p>
				</div>
				<div class="card-body">
					<form class="" action="" method="post">
  						{% csrf_token %}
  						{{ form|crispy }}
						<div class="form-group">
							<button class="btn btn-dark" type="submit ">Guardar</button>
							<a  href="{% url 'paginas:home' %}" class="btn btn-light" type="submit ">Cancelar</a>
						</div>
					</form>
				</div>
			</div>
	</div>
</div>
{% endblock content %}

templates/consultas/director_bitacoras.html
{% extends "base.html" %}

{% block title %}Bitacoras{% endblock title %}

{% block content %}
  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
              <a href="{% url 'Pacientes:Director_Lista_Recetas' %}" class="btn btn-primary btn-success btn-block">Bitacora recetas</a>
              <a href="{% url 'Pacientes:Director_Lista_Pacientes' %}" class="btn btn-primary btn-success btn-block">Bitacora pacientes</a>
              <a href="{% url 'Pacientes:Director_Lista_Citas' %}" class="btn btn-primary btn-success btn-block">Bitacora citas</a>
          </div>
        </div>

      </div>

    </div>

  </div>
{% endblock content %}

templates/consultas/dlist_citas.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}

{% block title %}Citas{% endblock title %}

{% block content %}
<table class="table table-striped">
    <th>ID</th>
    <th>Medico</th>
    <th>Registrada para cita con medico</th>
    <th>Paciente</th>
    <th>Fecha</th>
    {% for listcita in object_list %}
      <tr>
          <td>{{ listcita.id }}</td>
          <td>{{ listcita.creada_por }}</td>
          <td>{{ listcita.servicio }}</td>
          <td>{{ listcita.nombre_paciente }}</td>
          <td>{{ listcita.dia_hora_cita }}</td>

      </tr>
    {% endfor %}
</table>
<a  href="{% url 'Pacientes:Lista_Bitacoras' %}" class="btn btn-dark" style="float: right;" type="submit">Regresar</a>

{% endblock content %}

templates/consultas/dlist_pacientes.html
{% extends "base.html" %}

{% block title %}Pacientes{% endblock title %}

{% block content %}
<table class="table table-striped">
    <th>ID</th>
    <th>Medico</th>
    <th>Paciente</th>
    <th>Edad</th>
    <th>Descripcion</th>
    <th>Contacto</th>
    <th>Fecha de atencion</th>
    {% for listpacientes in object_list %}
      <tr>
          <td>{{ listpacientes.id }}</td>
          <td>{{ listpacientes.atendiendo }}</td>
          <td>{{ listpacientes.nombre }} {{ listpacientes.apellido_p }} {{ listpacientes.apellido_m }}</td>
          <td>{{ listpacientes.edad }}</td>
          <td>{{ listpacientes.descripcion }}</td>
          <td>{{ listpacientes.contacto }}</td>
          <td>{{ listpacientes.hora_atendido }}</td>
      </tr>
    {% endfor %}
</table>
<a  href="{% url 'Pacientes:Lista_Bitacoras' %}" class="btn btn-dark" style="float: right;" type="submit">Regresar</a>

{% endblock content %}

templates/consultas/dlist_recetas.html
{% extends "base.html" %}

{% block title %}Recetas{% endblock title %}

{% block content %}
<table class="table table-striped">
    <th>ID</th>
    <th>Medico</th>
    <th>Paciente</th>
    <th>Medicina</th>
    <th>Descripcion</th>
    <th>Fecha</th>
    {% for listrecetas in object_list %}
      <tr>
          <td>{{ listrecetas.id }}</td>
          <td>{{ listrecetas.creada_por }}</td>
          <td>{{ listrecetas.nombre_paciente  }}</td>
          <td>{{ listrecetas.medicina}}</td>
          <td>{{ listrecetas.descripcion }}</td>
          <td>{{ listrecetas.fecha_creada }}</td>

      </tr>
    {% endfor %}
</table>
<a  href="{% url 'Pacientes:Lista_Bitacoras' %}" class="btn btn-dark" style="float: right;" type="submit">Regresar</a>

{% endblock content %}

templates/consultas/list_cita_area.html
{% extends "base.html" %}

{% block title %}Citas{% endblock title %}

{% block content %}
  <table class="table table-striped">
    <th>ID</th>
    <th>Fecha Creado</th>
    <th>Creado Por</th>
    <th>Paciente</th>
    <th>Fecha de cita</th>
    {% for cit in citas %}
      <tr>
        <td>{{ cit.id }}</td>
        <td>{{ cit.fecha_creada  }}</td>
        <td>{{ cit.creada_por }}</td>
        <td>{{ cit.nombre_paciente }}</td>
        <td>{{ cit.dia_hora_cita }}</td>
      </tr>
    {% endfor %}
  </table>


{% endblock content %}

templates/consultas/list_recetas_area.html
{% extends "base.html" %}

{% block title %}Recetas{% endblock title %}

{% block content %}
  <table class="table table-striped">
      <th>ID</th>
      <th>Fecha Creado</th>
      <th>Creado Por</th>
      <th>Paciente</th>
      <th>Descripcion</th>
      <th>Vence</th>
      <th></th>
    {% for rec in recetas %}
      <tr>
          <td>{{ rec.id }}</td>
          <td>{{ rec.fecha_creada  }}</td>
          <td>{{ rec.creada_por }}</td>
          <td>{{ rec.nombre_paciente }}</td>
          <td>{{ rec.descripcion }}</td>
          <td>{{ rec.fecha_vencimiento }}</td>
          <td>
              <a href="{% url 'Pacientes:Receta_PDF' rec.id %}"><button type="button" id="btnEditar" class="btn btn-success btn-circle"><i class="fas fa-print fa-sm"></i></button></a>
          </td>
      </tr>
    {% endfor %}
  </table>


{% endblock content %}

templates/consultas/paciente_consulta.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Paciente consultado{% endblock title %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-3"></div>
			<div class="card col-6 my-4">
				<div class="card-header" style="background-color: #007fba; font-size: 18px;">
					<p class="text-center font-weight-bold" style="color: #fff;">Registrar Consulta nueva</p>
				</div>
				<div class="card-body">
					<form class="" action="" method="post">
  						{% csrf_token %}
  						{{ form|crispy }}
						<div class="form-group">
							<button class="btn btn-dark" type="submit ">Guardar</button>
							<a  href="{% url 'paginas:home' %}" class="btn btn-light" type="submit ">Cancelar</a>
						</div>
					</form>
				</div>
			</div>
	</div>
</div>
{% endblock content %}

templates/consultas/receta.html
<style>
 .titulos{
  font-size:20px;
  font-family:'Courier New';

  }
  .relleno{
  font-size:15px;
  font-family:'Courier New';
  text-decoration: underline;
  }
  .derecha{
  text-align:right;
  }
  .izquierda{
  text-align:left;
  }

</style>


{% csrf_token %}
{% for rec in recetas %}
<div id="encabezado">
 <p class="derecha">
 <span class="titulos">Fecha creado: </span> <span class="relleno">{{ rec.fecha_creada|date:"F d Y" }}</span>
 </p>
<br>
</div>
{% endfor %}


 {% for med in medico %}
 <span class="titulos">Medico:</span> <span class="relleno">{{ med.nombre }} {{ med.apellido_p }} {{ med.apellido_m }}</span>

{% endfor %}


 {% for rec in recetas %}
 <span class="titulos">Paciente:</span> <span class="relleno">{{ rec.nombre_paciente }}</span>
<p></p>
<span class="titulos">Medicina:</span> <span class="relleno">{{ rec.medicina }}</span>
<p></p>
 <span class="titulos">Descripcion:</span>  <span class="relleno">{{ rec.descripcion }}</span>
<p></p>
 <p class="titulos">Vencimiento: {{ rec.fecha_vencimiento|date:"F d Y" }}</p>
<p class="titulos" style="text-align:right">Firma del medico: ___________________</p>
{% endfor %}