Consultorio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView,logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("general.urls", namespace="home")),
    path('medico/',include('Medicos.urls')),
    path('paciente/',include('pacientes.urls')),

    path('accounts/login/',LoginView.as_view(template_name='paginas/login.html'),name='login'),
    path('logout/',logout_then_login,name='logout'),
]

Medicos/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import UsuarioRegistro, DirectorSeccion, ListMedicos, \
    ListServicios, CreateServicios, MedicoRegistro, DListMedicos, \
    DListServicios, DirectorUpdateMedico, EliminarMedico, DirectorUpdateServicio, \
    EliminarServicio

app_name='Medicos'
urlpatterns = [

    path('director/', DirectorSeccion.as_view(), name="Seccion_Director"),

    path('listMedicos/', ListMedicos.as_view(), name="List_Medicos"),
    path('dListaMedicos/', DListMedicos.as_view(), name="DLista_Medicos"),
    path('listServicios/', ListServicios.as_view(), name="List_Servicios"),
    path('dListaServicios/', DListServicios.as_view(), name="DLista_Servicios"),

    path('usuarioRegistro/',UsuarioRegistro.as_view(),name='Usuario_Registrar'),
    path('crearServicio/', CreateServicios.as_view(), name= "Crear_Servicio"),
    path('medicoRegistro/', MedicoRegistro.as_view(), name= "Medico_Registrar"),

    path('dUpdateMedico/<int:pk>/', DirectorUpdateMedico.as_view(), name="DUpdate_Medico"),
    path('dUpdateServicio/<int:pk>/', DirectorUpdateServicio.as_view(), name="DUpdate_Servicio"),

    path('EliminarMedico/<int:pk>/', EliminarMedico.as_view(), name="Eliminar_Medico"),
    path('EliminarServicio/<int:pk>/', EliminarServicio.as_view(), name="Eliminar_Servicio"),
]

general/urls.py
from django.urls import path

from general import views

app_name = "paginas"

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('informacion', views.Informacion.as_view(), name="Informacion"),
]

templates/paginas/actualizar_medico.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Crear medico nuevo{% endblock title %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-3"></div>
			<div class="card col-6 my-4">
				<div class="card-header" style="background-color: #007fba; font-size: 18px;">
					<p class="text-center font-weight-bold" style="color: #fff;">Registrar Servicio nuevo</p>
				</div>
				<div class="card-body">
					<form class="" action="" method="post">
  						{% csrf_token %}
  						{{ form|crispy }}
						<div class="form-group">
							<button class="btn btn-dark" type="submit ">Guardar Cambios</button>
							<a  href="{% url 'Medicos:DLista_Medicos' %}" class="btn btn-light" type="submit ">Cancelar</a>
						</div>
					</form>
				</div>
			</div>
	</div>
</div>
{% endblock content %}

templates/paginas/actualizar_servicio.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Actualizar servicio{% endblock title %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-3"></div>
			<div class="card col-6 my-4">
				<div class="card-header" style="background-color: #007fba; font-size: 18px;">
					<p class="text-center font-weight-bold" style="color: #fff;">Actualizar informacion de servicio</p>
				</div>
				<div class="card-body">
					<form class="" action="" method="post">
  						{% csrf_token %}
  						{{ form|crispy }}
						<div class="form-group">
							<button class="btn btn-dark" type="submit ">Guardar Cambios</button>
							<a  href="{% url 'Medicos:DLista_Servicios' %}" class="btn btn-light" type="submit ">Cancelar</a>
						</div>
					</form>
				</div>
			</div>
	</div>
</div>
{% endblock content %}

templates/paginas/crear_medico.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Crear medico nuevo{% endblock title %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-3"></div>
			<div class="card col-6 my-4">
				<div class="card-header" style="background-color: #007fba; font-size: 18px;">
					<p class="text-center font-weight-bold" style="color: #fff;">Registrar Medico nuevo</p>
				</div>
				<div class="card-body">
					<form class="" action="" method="post">
  						{% csrf_token %}
  						{{ form|crispy }}
						<div class="form-group">
							<button class="btn btn-dark" type="submit ">Guardar</button>
							<a  href="{% url 'Medicos:Seccion_Director' %}" class="btn btn-light" type="submit ">Cancelar</a>
						</div>
					</form>
				</div>
			</div>
	</div>
</div>
{% endblock content %}

templates/paginas/crear_usuario.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Crear Usuario{% endblock title %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-3"></div>
			<div class="card col-6 my-4">
				<div class="card-header" style="background-color: #007fba; font-size: 18px;">
					<p class="text-center font-weight-bold" style="color: #fff;">Crear usuario nuevo</p>
				</div>
				<div class="card-body">
					<form class="" action="" method="post">
  						{% csrf_token %}
  						{{ form|crispy }}
						<div class="form-group">
							<button class="btn btn-dark" type="submit ">Guardar</button>
							<a  href="{% url 'Medicos:Seccion_Director' %}" class="btn btn-light" type="submit ">Cancelar</a>
						</div>
					</form>
				</div>
			</div>
	</div>
</div>


{% endblock content %}

templates/paginas/director.html
{% extends "base.html" %}

{% block title %}Administrar Medicos{% endblock title %}

{% block content %}
  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
              <a href="{% url 'Medicos:Usuario_Registrar' %}" class="btn btn-primary btn-success btn-block">Crear nuevo usuario</a>
              <a href="{% url 'Medicos:Crear_Servicio' %}" class="btn btn-primary btn-success btn-block">Añadir servicio nuevo</a>
              <a href="{% url 'Medicos:Medico_Registrar' %}" class="btn btn-primary btn-success btn-block">Añadir medico nuevo</a>

              <a href="{% url 'Medicos:DLista_Medicos' %}" class="btn btn-primary btn-user btn-block">Editar medico</a>
              <a href="{% url 'Medicos:DLista_Servicios' %}" class="btn btn-primary btn-user btn-block">Editar servicio</a>

          </div>
        </div>

      </div>

    </div>

  </div>
{% endblock content %}

templates/paginas/dlista_medicos.html
{% extends "base.html" %}

{% block title %}Editar Medico{% endblock title %}

{% block content %}
<table class="table table-striped">
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Entrada</th>
    <th>Salida</th>
    <th>Dias que atiende</th>
    <th></th>
    {% for listmedicos in object_list %}
      <tr>
          <td>{{ listmedicos.nombre }}</td>
          <td>{{ listmedicos.apellido_p }}</td>
          <td>{{ listmedicos.entrada }}</td>
          <td>{{ listmedicos.salida }}</td>
          <td>{{ listmedicos.dias_de_trabajo }}</td>
          <td>
              <a href="{% url 'Medicos:DUpdate_Medico' listmedicos.id %}"><button type="button" id="btnEditar" class="btn btn-success btn-circle"><i class="fas fa-pen fa-sm"></i></button></a>
              <a href="{% url 'Medicos:Eliminar_Medico' listmedicos.id %}"><button type="button" name="button" id="btnEliminar" class="btn btn-danger btn-circle"><i class="fas fa-trash fa-sm"></i></button></a>
          </td>
    </tr>
    {% endfor %}

</table>
<a  href="{% url 'Medicos:Seccion_Director' %}" class="btn btn-dark" style="float: right;" type="submit">Regresar</a>

{% endblock content %}

templates/paginas/dlista_servicios.html
{% extends "base.html" %}

{% block title %}Editar Medico{% endblock title %}

{% block content %}
<table class="table table-striped">
    <th>ID</th>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th></th>
    {% for listservicios in object_list %}
      <tr>
          <td>{{ listservicios.id }}</td>
          <td>{{ listservicios.nombre }}</td>
          <td>{{ listservicios.descripcion }}</td>
          <td>
              <a href="{% url 'Medicos:DUpdate_Servicio' listservicios.id %}"><button type="button" id="btnEditar" class="btn btn-success btn-circle"><i class="fas fa-pen fa-sm"></i></button></a>
              <a href="{% url 'Medicos:Eliminar_Servicio' listservicios.id %}"><button type="button" name="button" id="btnEliminar" class="btn btn-danger btn-circle"><i class="fas fa-trash fa-sm"></i></button></a>
          </td>
      </tr>
    {% endfor %}
</table>
<a  href="{% url 'Medicos:Seccion_Director' %}" class="btn btn-dark" style="float: right;" type="submit">Regresar</a>

{% endblock content %}

templates/paginas/eliminar_medico.html
{% extends "base.html" %}

{% block title %}Eliminar Medico{% endblock title %}

{% block content %}
  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <form class="" action="" method="post">
                {% csrf_token %}
                <div class="card-body p-0">
                    Desea eliminar al medico: {{ object.nombre }} {{ object.apellido_p }} {{ object.apellido_m }}
                </div>
                <div class="form-group">
                    <button class="btn btn-dark" type="submit ">Eliminar Medico</button>
                    <a  href="{% url 'Medicos:DLista_Medicos' %}" class="btn btn-light" type="submit ">Cancelar</a>
                </div>
            </form>
        </div>

      </div>

    </div>

  </div>
{% endblock content %}

templates/paginas/eliminar_servicio.html
{% extends "base.html" %}

{% block title %}Eliminar Servicio{% endblock title %}

{% block content %}
  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <form class="" action="" method="post">
                {% csrf_token %}
                <div class="card-body p-0">
                    <p>Desea eliminar el servicio de: {{ object.nombre }}</p>
                    <p>Con descripcion: {{ object.descripcion}}</p>
                </div>
                <div class="form-group">
                    <button class="btn btn-dark" type="submit ">Eliminar Servicio</button>
                    <a  href="{% url 'Medicos:DLista_Servicios' %}" class="btn btn-light" type="submit ">Cancelar</a>
                </div>

            </form>
        </div>

      </div>

    </div>

  </div>
{% endblock content %}

templates/paginas/home.html
{% extends "base.html" %}

{% block title %} Home {% endblock title %}
{% block content %}
<div class="row">
	<div class="col">
		<div class="jumbotron jumbotron-fluid bg-jumbotron" style="">
			<div class="container ">
				<h1 class=" fnt-color display-4" >Consultorio galgos</h1>
				<p class="lead fnt-color"> La mejor atencion al alcance de tus manos</p>
			</div>
		</div>
		<div class="container">
		<div class="row">
			<div class="col-4">
				<div class="card">
					<img src="static/img/medico-con-paciente.jpeg" class="card-img-top">
					<div class="card-body">
						<h5 class="card-title">Calidad</h5>
						<p class="card-text"> Atencion a nuestros pacientes de manera debida.</p>
					</div>
				</div>
			</div>
			<div class="col-4">
				<div class="card">
					<img src="static/img/manos-medico.jpeg" class="card-img-top">
					<div class="card-body">
						<h5 class="card-title">Privacidad</h5>
						<p class="card-text"> Protegemos la identidad de nuestros pacientes al igual que sus situaciones.</p>
					</div>
				</div>
			</div>
			<div class="col-4">
				<div class="card">
					<img src="static/img/medico-paciente.jpeg" class="card-img-top">
					<div class="card-body">
						<h5 class="card-title">Diagnosticos certeros</h5>
						<p class="card-text">  Contamos con tecnologia de calidad y medicos capacitados para atender a los pacientes.</p>
					</div>
				</div>
			</div>
		</div>

		<div class="row py-4">
			<div class="col-4">
				<div class="card">
					<img src="static/img/medico-con-mujer.jpeg" class="card-img-top">
					<div class="card-body">
						<h5 class="card-title">Equidad</h5>
						<p class="card-text"> Cada paciente y familiar reciben un trato digno y oportuno, priorizando la atención médica de acuerdo con sus condiciones de salud y sus necesidades.</p>
					</div>
				</div>
			</div>
			<div class="col-4">
				<div class="card">
					<img src="static/img/medicos-y-pacientes.png" class="card-img-top">
					<div class="card-body">
						<h5 class="card-title">Humanismo</h5>
						<p class="card-text"> Conducimos en la relación con los pacientes y familiares respetando siempre su dignidad, sus derechos y valor como personas.</p>
					</div>
				</div>
			</div>
			<div class="col-4">
				<div class="card">
					<img src="static/img/paciente-coronavirus.jpeg" class="card-img-top">
					<div class="card-body">
						<h5 class="card-title">Responsabilidad</h5>
						<p class="card-text"> Asumimos a cabalidad los deberes de las funciones que se tienen asignadas.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
</div>
{% endblock content %}

templates/paginas/list_medicos.html
{% extends "base.html" %}

{% block title %}Medicos{% endblock title %}

{% block content %}
<table class="table table-striped">
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Servicio</th>
    <th>Entrada</th>
    <th>Salida</th>
    <th>Dias que atiende</th>
    {% for listmedicos in object_list %}
      <tr>
          <td>{{ listmedicos.nombre }}</td>
          <td>{{ listmedicos.apellido_p }} {{ listmedicos.apellido_m }}</td>
          <td>{{ listmedicos.servicio }}</td>
          <td>{{ listmedicos.entrada }}</td>
          <td>{{ listmedicos.salida }}</td>
          <td>{{ listmedicos.dias_de_trabajo }}</td>
      </tr>
    {% endfor %}
</table>

{% endblock content %}

templates/paginas/list_servicios.html
{% extends "base.html" %}

{% block title %}Servicios{% endblock title %}

{% block content %}
<table class="table table-striped">
    <th>Servicio</th>
    <th>Descripcion</th>
    <th>Costo</th>
    {% for listservicios in object_list %}
      <tr>
          <td>{{ listservicios.nombre }}</td>

          <td>{{ listservicios.descripcion}}</td>

          <td>Costos consultables en recepcion o por telefono</td>
      </tr>
    {% endfor %}
</table>

{% endblock content %}

templates/paginas/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock title %}

{% block content %}

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Iniciar sesión</h1>
                    <small class="text-danger">
                      {% if form.errors  %}
                       Usuario o contraseña incorrectos
                      {% endif %}
                    </small>
                  </div>
                  <form class="user" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" name="username" id="id_username" aria-describedby="usuario" placeholder="Ingresar usuario">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" name="password" id="id_password" placeholder="Contraseña">
                    </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block">Login</button>
                    <a href="{% url 'paginas:home' %}" class="btn btn-danger btn-user btn-block">Cancelar</a>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

{% endblock content %}

templates/paginas/registroMedico.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Registro de Medico{% endblock title %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-3"></div>
			<div class="card col-6 my-4">
				<div class="card-header" style="background-color: #007fba; font-size: 18px;">
					<p class="text-center font-weight-bold" style="color: #fff;">Registro de Medico Nuevo</p>
				</div>
				<div class="card-body">
					<form class="" action="" method="post">
  						{% csrf_token %}
  						{{ form|crispy }}
						<div class="form-group">
							<button class="btn btn-dark" type="submit ">Guardar</button>
							<a  href="{% url 'Medicos:Seccion_Director' %}" class="btn btn-light" type="submit ">Cancelar</a>
						</div>
					</form>
				</div>
			</div>
	</div>
</div>


{% endblock content %}