Consultorio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView,logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("general.urls", namespace="home")),
    path('medico/',include('Medicos.urls')),
    path('paciente/',include('pacientes.urls')),

    path('accounts/login/',LoginView.as_view(template_name='paginas/login.html'),name='login'),
    path('logout/',logout_then_login,name='logout'),
]

Medicos/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import UsuarioRegistro, DirectorSeccion, ListMedicos, \
    ListServicios, CreateServicios, MedicoRegistro, DListMedicos, \
    DListServicios, DirectorUpdateMedico, EliminarMedico, DirectorUpdateServicio, \
    EliminarServicio

app_name='Medicos'
urlpatterns = [

    path('director/', DirectorSeccion.as_view(), name="Seccion_Director"),

    path('listMedicos/', ListMedicos.as_view(), name="List_Medicos"),
    path('dListaMedicos/', DListMedicos.as_view(), name="DLista_Medicos"),
    path('listServicios/', ListServicios.as_view(), name="List_Servicios"),
    path('dListaServicios/', DListServicios.as_view(), name="DLista_Servicios"),

    path('usuarioRegistro/',UsuarioRegistro.as_view(),name='Usuario_Registrar'),
    path('crearServicio/', CreateServicios.as_view(), name= "Crear_Servicio"),
    path('medicoRegistro/', MedicoRegistro.as_view(), name= "Medico_Registrar"),

    path('dUpdateMedico/<int:pk>/', DirectorUpdateMedico.as_view(), name="DUpdate_Medico"),
    path('dUpdateServicio/<int:pk>/', DirectorUpdateServicio.as_view(), name="DUpdate_Servicio"),

    path('EliminarMedico/<int:pk>/', EliminarMedico.as_view(), name="Eliminar_Medico"),
    path('EliminarServicio/<int:pk>/', EliminarServicio.as_view(), name="Eliminar_Servicio"),
]

general/urls.py
from django.urls import path

from general import views

app_name = "paginas"

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('informacion', views.Informacion.as_view(), name="Informacion"),
]

pacientes/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import CrearConsulta, CrearCita, CrearReceta, MedicoConsultarCitas, BitacorasSeccion, \
    DirectorListaRecetas, DirectorListaPacientes, DirectorListaCitas, MedicoConsultarRecetas, \
    GeneratePDF, MedicoCitasCreadas, GeneratePDF2

app_name='Pacientes'

urlpatterns = [
    path('listaBitacoras/', BitacorasSeccion.as_view(), name="Lista_Bitacoras"),

    path('crearConsulta/', CrearConsulta.as_view(), name="Crear_Consulta"),
    path('crearCita/', CrearCita.as_view(), name="Crear_Cita"),
    path('crearReceta/', CrearReceta.as_view(), name="Crear_Receta"),

    path('consultarCitas/<int:pk>/', MedicoConsultarCitas, name="Consultar_citas"),
    path('consultarRecetas/<int:pk>/', MedicoConsultarRecetas, name="Consultar_recetas"),
    path('citasCreadas/<int:pk>/', MedicoCitasCreadas, name="Citas_Creadas"),

    path('listaRecetas/', DirectorListaRecetas.as_view(),name="Director_Lista_Recetas"),
    path('listaPacientes/', DirectorListaPacientes.as_view(),name="Director_Lista_Pacientes"),
    path('listaCitas/', DirectorListaCitas.as_view(),name="Director_Lista_Citas"),

    path('recetaPDF/<int:pk>/', GeneratePDF.as_view(), name="Receta_PDF"),
    path('citaPDF/<int:pk>/', GeneratePDF2.as_view(), name="Cita_PDF"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock title %}</title>

  <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
  <div id="wrapper">
    <div id="content-wrapper" class="d-flex flex-column">
      <div id="content">
{% block navbar %}
          <nav class="navbar navbar-dark " style="background-color: #4e73df">
		<a class="navbar-brand" href="{% url 'paginas:home'%}">Inicio</a>
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link fnt-color" href="{% url 'paginas:Informacion'%}" style="color: #fff;">Informacion</a>
				</li>
		    </ul>
            <ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link fnt-color" href="{% url 'Medicos:List_Servicios'%}" style="color: #fff;">Servicios</a>
				</li>
		    </ul>
            <ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link fnt-color" href="{% url 'Medicos:List_Medicos'%}" style="color: #fff;">Medicos</a>
				</li>
		    </ul>
        {% if request.user.is_superuser %}
        <div class="dropdown">
            <a class="dropbtn" style="color:#fff;">Usuario: <b>{{ request.user.username }}</b></a>
            <div class="dropdown-content">
                <a href="{% url 'Medicos:Seccion_Director' %}">Medicos & Servicios</a>
                <a href="{% url 'Pacientes:Lista_Bitacoras' %}">Pacientes & Recetas</a>
                <a href="{% url 'Pacientes:Crear_Consulta' %}">Crear consulta</a>
                <a href="{% url 'Pacientes:Crear_Cita' %}">Crear cita</a>
                <a href="{% url 'Pacientes:Crear_Receta' %}">Crear recetas</a>
                <a href="{% url 'logout'%}">Logout</a>
            </div>
        </div>
        {% elif request.user.is_active %}
        <div class="dropdown">
            <a class="dropbtn" style="color:#fff;">Usuario: <b>{{ request.user.username }}</b></a>
            <div class="dropdown-content">
                <a href="{% url 'Pacientes:Crear_Consulta' %}">Paciente</a>
                <a href="{% url 'Pacientes:Crear_Cita' %}">Crear cita</a>
                <a href="{% url 'Pacientes:Crear_Receta' %}">Crear receta</a>
                <a href="{% url 'Pacientes:Consultar_citas' request.user.id %}">Citas en area</a>
                <a href="{% url 'Pacientes:Consultar_recetas' request.user.id %}">Recetas creadas</a>
                <a href="{% url 'Pacientes:Citas_Creadas' request.user.id %}">Citas creadas</a>
                <a href="{% url 'logout'%}">Logout</a>
            </div>
        </div>
	    {% else %}
        <a href="{% url 'login'%}"style="color:#fff;">Login <b></b></a>
        {% endif %}
          </nav>

{% endblock navbar %}

{% block content %}
        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->
{% endblock content %}
{% block footer %}
      <!-- Footer -->
      <footer style="margin-top: 300px;">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span style="lenght:400px;">Copyright &copy; Your Website 2020</span>

          </div>
        </div>
      </footer>
      <!-- End of Footer -->
{% endblock footer %}
    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>
</html>